name: Build
on: [push]
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: golangci/golangci-lint-action@v3
      - run: go vet
      - run: go test ./...
      - run: go build